**Loading Required Dependencies**

In [12]:
import numpy as np 
import time
import os
import random as rd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

"""
start at 0 x 0 goal at n-1 x n-1 assuming a square grid
1 = obstacles
0 = possible path
"""


'\nstart at 0 x 0 goal at n-1 x n-1 assuming a square grid\n1 = obstacles\n0 = possible path\n'

Creating Map of the World for the robot

---



---



In [13]:
def get_map():
    """
    setting obstacles 
    fucntion to return the map array
    """
    map = np.zeros((8,8), dtype=str)
    # for i in range(6):
    #   for j in range(6):
    #     map[i][j] = rd.randint(0,1)
    map[3][4] = 1
    map[1][2] = 1
    map[2][1] = 1
    map[3][3] = 1
    map[6][2] = 1
    map[6][6] = 1

    return map

In [14]:
map = get_map()

In [15]:
print (map)

[['' '' '' '' '' '' '' '']
 ['' '' '1' '' '' '' '' '']
 ['' '1' '' '' '' '' '' '']
 ['' '' '' '1' '1' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '1' '' '' '' '1' '']
 ['' '' '' '' '' '' '' '']]


Generating Adjacency Matrix

---



---


*useful to represent which vertices (or nodes) of a graph are adjacent to 
which other vertices.*

In [16]:
# generate adj matrix
new_adj = [[] for i in range(64)];
z = len(map) * len(map)
n = len(map)
print(n)        #making sure the value of n
adj = np.zeros((z,z), dtype=int)
def generate_adj(grid):
  for i in range(n):
    for j in range(n):
      for x, y in ((i-1,j),(i,j-1),(i,j+1),(i+1,j),(i-1,j-1),(i+1,j-1),(i-1,j+1),(i+1,j+1)): #(i-1,j),(i,j-1),(i,j+1),(i+1,j) keep this for 4-connectivity
        if 0 <= x < n and 0 <= y < n and map[x][y] == '':
          adj[i*n+j][x*n+y] = 1 # converted 1-D index to 2D index
          add_edge(new_adj, i*n+j, x*n+y)
  # print(adj)

def add_edge(adj, src, dest):
    adj[src].append(dest);
    adj[dest].append(src);

8


In [17]:
generate_adj(map)

In [18]:
print(adj)
print(new_adj)

[[0 1 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 1 0]]
[[1, 8, 9, 1, 8, 9], [0, 0, 2, 9, 8, 2, 8, 9, 10], [1, 1, 3, 9, 11, 3, 9, 10, 11], [2, 2, 4, 11, 12, 4, 10, 11, 12], [3, 3, 5, 12, 11, 13, 5, 11, 12, 13], [4, 4, 6, 13, 12, 14, 6, 12, 13, 14], [5, 5, 7, 14, 13, 15, 7, 13, 14, 15], [6, 6, 15, 14, 14, 15], [0, 1, 0, 9, 16, 1, 9, 16, 17], [0, 1, 2, 8, 1, 8, 0, 16, 2, 18, 10, 16, 17, 18], [2, 9, 11, 18, 1, 3, 19], [2, 3, 4, 10, 3, 12, 19, 2, 18, 4, 20, 12, 18, 19, 20], [3, 4, 5, 11, 4, 11, 13, 20, 3, 19, 5, 21, 13, 19, 20, 21], [4, 5, 6, 12, 5, 12, 14, 21, 4, 20, 6, 22, 14, 20, 21, 22], [5, 6, 7, 13, 6, 13, 15, 22, 5, 21, 7, 23, 15, 21, 22, 23], [6, 7, 14, 7, 14, 23, 6, 22, 22, 23], [8, 9, 8, 24, 9, 25, 17, 24, 25], [9, 16, 18, 25, 8, 24, 26], [9, 10, 11, 17, 19, 26, 9, 25, 11, 19, 25, 26, 27], [10, 11, 12, 18, 11, 18, 20, 26, 12, 20, 26, 27, 28], [11, 12, 13, 19, 12, 19, 21, 11, 13, 29, 21, 27, 28, 29], [12, 13, 14, 20, 

**To find the shortest path i used Simple Breath First Search Algorithm (BFS)**

---
*here I used R to show the movement of the robot*

In [19]:
def BFS(adj, src, dest, v, pred, dist):
 
    # a queue to maintain queue of vertices whose
    # adjacency list is to be scanned as per normal
    queue = []
  
    # boolean array visited[] which stores the
    # information whether ith vertex is reached
    # at least once in the Breadth first search
    visited = [False for i in range(v)];
  
    # initially all vertices are unvisited
    # so v[i] for all i is false
    # and as no path is yet constructed
    # dist[i] for all i set to infinity
    for i in range(v):
 
        dist[i] = 1000000
        pred[i] = -1;
     
    # now source is first to be visited and
    # distance from source to itself should be 0
    visited[src] = True;
    dist[src] = 0;
    queue.append(src);
  
    # standard BFS algorithm
    while (len(queue) != 0):
        u = queue[0];
        queue.pop(0);
        # a = queue.pop(0);
        for i in range(len(adj[u])):
         
            if (visited[adj[u][i]] == False):
                visited[adj[u][i]] = True;
                print(adj[u][i])
                dist[adj[u][i]] = dist[u] + 1;
                pred[adj[u][i]] = u;
                queue.append(adj[u][i]);
                # print(a, end ="")
  
                # We stop BFS when we find
                # destination.
                if (adj[u][i] == dest):
                    return True;
  
    return False;
  
# utility function to print the shortest distance
# between source vertex and destination vertex
def printShortestDistance(adj, s, dest, v):
     
    # predecessor[i] array stores predecessor of
    # i and distance array stores distance of i
    # from s
    
    pred=[0 for i in range(v)]
    dist=[0 for i in range(v)];

  
    if (map[0][0] == 1 or BFS(adj, s, dest, v, pred, dist) == False):
        print("Given source and destination are not connected")
        return
  
    # vector path stores the shortest path
    path = []
    crawl = dest;
    crawl = dest;
    path.append(crawl);
     
    while (pred[crawl] != -1):
        path.append(pred[crawl]);
        crawl = pred[crawl]; 
  
    # distance from source is in distance array
    print("Shortest path length is : " + str(dist[dest]), end = '')
  
    # printing path from source to destination
    print("\nPath is : : ")
     
    for i in range(len(path)-1, -1, -1):
        print(path[i], end=' ')

    #visualized path in map variable
    for p in path:
      x = p//8
      y = p%8
      map[x][y] = 'R'
    
    # map[6][6] = 'G'
    # map[0][0] = 'S'
      

In [20]:
# # this creates new adj
# new_adj = [[] for i in range(36)];
# for i in range(36):
#   for j in range(36):
#     if adj[i][j] == 1:
#       add_edge(new_adj, i, j)

Marking / Setting the Start (S) and Goal (G) points. 

In [21]:
def get_shortest_path(start, end, map):
    "function to get the map and visualize the shortest path"
    printShortestDistance(new_adj, start, end, 64)
    print("\n\n",start, end)
    map[start//8][start%8] = 'S'
    map[end//8][end%8] = 'G'
    print(map)

Final Output

---
*printing the output*


In [22]:
#get the final outputs
for i in range(0,3):        #change for how many times you need the output to be generated
    start = rd.randint(0,63)
    end = rd.randint(0,63)
    map = get_map()
    print("\n------Shortest path for matrix {}-------".format(i))
    get_shortest_path(start, end, map)


------Shortest path for matrix 0-------
5
6
7
13
15
22
21
23
4
12
20
30
29
31
28
3
11
19
27
38
Shortest path length is : 3
Path is : : 
14 22 30 38 

 14 38
[['' '' '' '' '' '' '' '']
 ['' '' '1' '' '' '' 'S' '']
 ['' '1' '' '' '' '' 'R' '']
 ['' '' '' '1' '1' '' 'R' '']
 ['' '' '' '' '' '' 'G' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '1' '' '' '' '1' '']
 ['' '' '' '' '' '' '' '']]

------Shortest path for matrix 1-------
44
45
46
52
61
60
62
54
35
36
37
43
51
38
39
47
55
59
63
26
27
28
34
42
29
30
50
58
31
17
18
19
25
33
20
21
41
49
22
23
57
9
16
8
24
10
11
12
32
40
13
14
48
56
15
Shortest path length is : 5
Path is : : 
53 44 36 29 22 15 

 53 15
[['' '' '' '' '' '' '' '']
 ['' '' '1' '' '' '' '' 'G']
 ['' '1' '' '' '' '' 'R' '']
 ['' '' '' '1' '1' 'R' '' '']
 ['' '' '' '' 'R' '' '' '']
 ['' '' '' '' 'R' '' '' '']
 ['' '' '1' '' '' 'S' '1' '']
 ['' '' '' '' '' '' '' '']]

------Shortest path for matrix 2-------
46
47
54
63
62
37
38
39
45
53
61
28
29
30
36
44
31
52
60
20
19
35
21
22
2